name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: ls
